# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bglky Blog
SEOTitle: 周炳光的博客 | Bglky Blog
email: bglky.me@gmail.com
keywords: "周炳光,bglky,周炳光的博客,bglky blog,赖柯滢,responsive,blog,framework7,jekyll"
description: "An awesome SPA and responsive blog based on Framework7 and Jekyll!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bglky.me" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

gems: [jekyll-paginate]

exclude: [".project"]
paginate: 10
disqus_username: bglky






# Side-panel
side-panel: true                        # whether or not using Side-panel

# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# Socials
socials: true                           # whether or not using Socials
introduction: One sentence introducing yourself of what you do. #One sentence introducing yourself of what you do
avatar: /img/avatar.jpg                 # the path to your avatar
RSS: false
github_username: bglky
twitter_username: zhoubglky
facebook_username: 

# Friends
friends: [
    {
        title: "Hansome",
        href: "http://it198.com"
    }
]